{% set name = "sphinx-reredirects" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # NOTE : tarball has an underscore
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_reredirects-{{ version }}.tar.gz
  sha256: 7c9bada9f1330489fcf4c7297a2d6da2a49ca4877d3f42d1388ae1de1019bf5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sphinx

test:
  imports:
    - sphinx_reredirects
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://gitlab.com/documatt/sphinx-reredirects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handles redirects for moved pages in Sphinx documentation projects
  doc_url: https://documatt.gitlab.io/sphinx-reredirects
  dev_url: https://gitlab.com/documatt/sphinx-reredirects

extra:
  recipe-maintainers:
    - moorepants
