{% set name = "sphinx-reredirects" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # NOTE : tarball has an underscore
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_reredirects-{{ version }}.tar.gz
  sha256: b8effdb31a069823cd8b5b029bfe1e04ac584615a0ebea35c5a8c8daf05a354b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx

test:
  imports:
    - sphinx_reredirects
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/documatt/sphinx-reredirects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handles redirects for moved pages in Sphinx documentation projects
  doc_url: https://documatt.gitlab.io/sphinx-reredirects
  dev_url: https://gitlab.com/documatt/sphinx-reredirects

extra:
  recipe-maintainers:
    - moorepants
