{% set name = "sphinx-reredirects" %}
{% set version = "1.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # NOTE : tarball has an underscore
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_reredirects-{{ version }}.tar.gz
  sha256: fb9b195335ab14b43f8273287d0c7eeb637ba6c56c66581c11b47202f6718b29

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - sphinx >=7.4

test:
  imports:
    - sphinx_reredirects
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://documatt.com/sphinx-reredirects
  license: MIT
  license_file: LICENSE
  summary: Handles redirects for moved pages in Sphinx documentation projects
  doc_url: https://documatt.com/sphinx-reredirects
  dev_url: https://github.com/documatt/sphinx-reredirects

extra:
  recipe-maintainers:
    - moorepants
