{% set name = "sphinx-reredirects" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # NOTE : tarball has an underscore
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_reredirects-{{ version }}.tar.gz
  sha256: a0e7213304759b01edc22f032f1715a1c61176fc8f167164e7a52b9feec9ac64

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx

test:
  imports:
    - sphinx_reredirects
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.com/documatt/sphinx-reredirects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handles redirects for moved pages in Sphinx documentation projects
  doc_url: https://documatt.gitlab.io/sphinx-reredirects
  dev_url: https://gitlab.com/documatt/sphinx-reredirects

extra:
  recipe-maintainers:
    - moorepants
